### ISSUE TITLE
Pypi release

### ISSUE THREAD

**Issue by tomgross** [collective/redomino.tokenrole#9]
I updated this package to work with Plone 5.0 and 5.1 and want to make a release. Since this package doesn't seem to be maintained be redomino any more can someone give me authoring rights on pypi. My username is _iT0m_. Thanks!

**Comment by davidemoro** [comment]
Hi Tom,

I am sorry but my user on pypi doesn't have any grants on
redomino.tokenrole.

I think @realefab might help you!

Il 07/apr/2017 22:37, "Tom Gross" <notifications@github.com> ha scritto:

**Comment by sithmel** [comment]
@tomgross I gave you the maintainer role. Let me know if it is not enough

**Comment by tomgross** [comment]
Worked perfect! Thanks @sithmel and @rafaelbco 
https://pypi.python.org/pypi/redomino.tokenrole/1.0b2
